name: Post-bottle-build steps
description: Runs the common steps to be done after building bottles.
inputs:
  bottles-directory:
    description: Bottles directory
    required: true
  logs-directory:
    description: Logs directory
    required: true
  runner:
    description: Runner label
    required: true
  cleanup:
    description: Do cleanup steps?
    required: false
    default: true
  upload-bottles:
    description: Upload built bottles?
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Failures summary for brew test-bot
      if: always()
      uses: Homebrew/actions/failures-summary-and-bottle-result@master
      with:
        workdir: ${{ inputs.bottles-directory }}
        result_path: steps_output.txt
        step_name: "Steps summary on ${{ inputs.runner }}"

    - name: Output brew linkage result
      if: always()
      uses: Homebrew/actions/failures-summary-and-bottle-result@master
      with:
        workdir: ${{ inputs.bottles-directory }}
        result_path: linkage_output.txt
        step_name: "`brew linkage` output on ${{ inputs.runner }}"
        collapse: true

    - name: Output brew bottle result
      if: always()
      uses: Homebrew/actions/failures-summary-and-bottle-result@master
      with:
        workdir: ${{ inputs.bottles-directory }}
        result_path: bottle_output.txt
        step_name: "`brew bottle` output on ${{ inputs.runner }}"
        collapse: true

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: logs_${{ inputs.runner }}
        path: ${{ inputs.logs-directory }}

    - name: Count bottles
      id: bottles
      if: always()
      run: |
        "${GITHUB_ACTION_PATH}/count-bottles.sh" "${DEBUG}"
      working-directory: ${{ inputs.bottles-directory }}
      shell: /bin/bash -euo pipefail {0}
      env:
        DEBUG: ${{ runner.debug == '1' }}

    - name: Upload failed bottles
      if: always() && steps.bottles.outputs.failures > 0
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: failed-bottles_${{ inputs.runner }}
        path: ${{ inputs.bottles-directory }}/failed

    - name: Upload list of successfully tested dependents
      if: always() && !fromJson(inputs.upload-bottles) && steps.bottles.outputs.dependents > 0
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: dependents_${{ inputs.runner }}
        path: ${{ inputs.bottles-directory }}/tested-dependents-*.txt

    # Must be run before the `Upload bottles` step so that failed
    # bottles are not included in the `bottles` artifact.
    - name: Delete unneeded files
      if: always()
      run: |
        rm -rvf logs home failed artifact-cache
        rm -rvf tested-dependents-*.txt
      working-directory: ${{ inputs.bottles-directory }}
      shell: /bin/bash -euo pipefail {0}

    - name: Upload bottles
      if: always() && fromJson(inputs.upload-bottles) && (steps.bottles.outputs.count > 0 || steps.bottles.outputs.skipped > 0)
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: bottles_${{ inputs.runner }}
        path: ${{ inputs.bottles-directory }}

    - name: Post cleanup
      if: always() && fromJson(inputs.cleanup)
      run: |
        brew test-bot --only-cleanup-after
        rm -rvf "${BOTTLES_DIR:?}"
      shell: /bin/bash -euo pipefail {0}
      env:
        BOTTLES_DIR: ${{ inputs.bottles-directory }}
