name: setup-commit-signing
description: Set up SSH commit signing
author: nandahkrishna
branding:
  icon: user-check
  color: green
inputs:
  signing_key:
    description: SSH private key to use for signing commits
    required: true
  ssh:
    description: "[DEPRECATED] Whether to do SSH signing"
    required: false
    deprecationMessage: "Has no effect; SSH signing is always used"
    default: "false"
runs:
  using: composite
  steps:
    - name: Enable SSH agent
      run: | # zizmor: ignore[github-env]
        eval $(ssh-agent)

        echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> ${GITHUB_ENV}
        echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> ${GITHUB_ENV}
      shell: bash

    - name: Configure SSH signing
      run: |
        # Defensively mask the signing key. It should already be masked
        # if it comes from a secret, but just in case.
        echo "${SIGNING_KEY}" | sed 's/^ */::add-mask::/'
        "$GITHUB_ACTION_PATH/main.sh" "$SIGNING_KEY"
      shell: bash
      id: setup-ssh
      env:
        SIGNING_KEY: ${{ inputs.signing_key }}
