name: Bump formulae
description: Bump (update) Homebrew outdated formulae
author: dawidd6
branding:
  icon: arrow-up-circle
  color: yellow
inputs:
  token:
    description: GitHub token (not the default one)
    required: true
  formulae:
    description: Formula names, space-separated
    required: true
runs:
  using: composite
  steps:
    - run: echo "::warning::Homebrew/actions/bump-formulae is deprecated. Please use Homebrew/actions/bump-packages instead."
      shell: sh

    - uses: Homebrew/actions/bump-packages@main
      with:
        token: ${{ inputs.token }}
        formulae: ${{ inputs.formulae }}
