name: Git try push

on:
  pull_request:
    paths:
      - '**git-try-push**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

permissions:
  contents: read

jobs:
  try-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare remote
        run: |
          git init --bare "${RUNNER_TEMP}/remote-repo"
          git remote add local-remote "file://${RUNNER_TEMP}/remote-repo"

      - name: Prepare
        run: |
          git checkout -b test-try-push
          git push local-remote test-try-push
          git reset --hard HEAD~1
          git checkout -

      - name: Push
        uses: ./git-try-push/
        with:
          remote: local-remote
          branch: test-try-push
