name: Git user config

on:
  pull_request:
    paths:
      - '**git-user-config**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

jobs:
  user-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Config
        id: config
        uses: ./git-user-config/
        with:
          username: BrewTestBot

      - name: Test
        env:
          CONFIG_OUTPUT_NAME: ${{steps.config.outputs.name}}
          CONFIG_OUTPUT_EMAIL: ${{steps.config.outputs.email}}
        run: |
          test "$CONFIG_OUTPUT_NAME" = "BrewTestBot"
          test "$CONFIG_OUTPUT_EMAIL" = "1589480+BrewTestBot@users.noreply.github.com"
          test "$(git config --global user.name)" = "BrewTestBot"
          test "$(git config --global user.email)" = "1589480+BrewTestBot@users.noreply.github.com"
