name: Wait for idle runner

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**wait-for-idle-runner**"
      - "package.json"
      - "package-lock.json"
      - "node_modules/**"

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check scripts
        run: node --check wait-for-idle-runner/main.js
